@hostname=localhost
@port=3000

POST http://{{hostname}}:{{port}}/api/products
Content-Type: application/json

{
  "name": "monitor",
  "price": "hola"
}

###

GET http://{{hostname}}:{{port}}/api/products

###

GET http://{{hostname}}:{{port}}/api/products/8

###

PUT http://{{hostname}}:{{port}}/api/products/11
Content-Type: application/json

{
  "name": "monitor",
  "price": 300,
  "availability": false
}

###

PATCH http://{{hostname}}:{{port}}/api/products/11

###

DELETE http://{{hostname}}:{{port}}/api/products/80
